### ISSUE TITLE
Unhandled Exception: Text length must be less than 64 characters long

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eyal0/no-doze#1]
```
What steps will reproduce the problem?
1. Add a pattern which matches a running process with more than 64 characters 
in length, e.g.: the pattern "*cudaminer*" matches "C:\Windows\system32\cmd.exe 
- cudaminer.exe  -o stratum+tcp://asia.mine-litecoin.com -O username.worker:x" 
2. Observe the error:

"Unhandled exception has occurred in your application. If you click Continue, 
the application will ignore this error and attempt to continue. If you click 
Quit, the application will close immediately.

Text length must be less than 64 characters long.
Parameter name text

Actual value was NoDoze Options - Awake for: Administrator: 
C:\Windows\system32\cmd.exe - cudaminer.exe  -o 
stratum+tcp://asia.mine-litecoin.com -O username.worker:x.
   at System.Windows.Forms.NotifyIcon.set_Text(String value)
   at NoDoze.NoDozeOptions.UpdateIcon(Boolean full, String reason)
   at NoDoze.NoDozeOptions.ProcessesTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1008 (RTMGDR.030319-1000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NoDoze
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/apps/nodoze/NoDoze-1.1.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.233 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1002 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1001 built by: RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
"

3. Click Continue and observe that the error repeats indefinitely.
```

Original issue reported on code.google.com by `dhel...@gmail.com` on 21 Nov 2013 at 2:32

**Comment by GoogleCodeExporter** [comment]
```
Fix was simple - on the Icon.SetText call, do a length check and make sure not 
to set text on an icon with more than 64 charcacters.  Note that uninstall / 
reinstall fails to fix the problem because the text is stored in the registry.  
To avoid the problem, do not add any long exe names (like you see in Chrome 
apps) :

   Dim icontext As String
            icontext = Me.Text + " - Awake for: " + reason
            If (icontext.Length > 62) Then
                icontext = icontext.Substring(0, 62)
            End If

            NotifyIcon1.Text = icontext
```

Original comment by `rspren...@gmail.com` on 30 Nov 2014 at 7:01
